Amsterdam/zaken-frontend

.env.development, .env.production, package-lock.json, package.json, scripts/generateFormScaffolds.ts, scripts/generateSwaggerSchema.ts, scripts/tsconfig.json, scripts/utils/url.utils.ts, src/__generated__/POST_Cases.json, src/__generated__/PUT_Cases.json, src/app/state/state/config.ts
=> feat: introduce .env files

src/__generated__/POST_Cases.json, src/__generated__/PUT_Cases.json, src/app/features/cases/components/organisms/FormEdit/FormEdit.tsx, src/app/features/cases/components/organisms/TableCases/TableCases.tsx, src/app/features/cases/components/pages/edit/EditPage.tsx, src/app/features/cases/hooks/useCaseByUUID.ts, src/app/features/shared/components/atoms/SpinnerButton/SpinnerButton.stories.tsx, src/app/features/shared/components/atoms/SpinnerButton/SpinnerButton.tsx, src/app/features/shared/components/molecules/ConfirmButton/ConfirmButton.stories.tsx, src/app/features/shared/components/molecules/ConfirmButton/ConfirmButton.tsx, src/app/features/shared/components/molecules/Modal/ConfirmModal.tsx, src/app/features/shared/components/molecules/Modal/Modal.stories.tsx, src/app/features/shared/components/molecules/Modal/Modal.tsx, src/app/features/shared/components/molecules/Modal/hooks/useModal.tsx
=> Actually edit and delete a case

package-lock.json, package.json, src/app/features/cases/components/organisms/FormEdit/FormEdit.tsx, src/app/features/cases/components/pages/edit/EditPage.tsx, src/app/features/cases/hooks/useCaseByUUID.ts
Show spinner in form when data is not loaded yet.
=> feat: show form spinner

src/app/features/cases/components/pages/home/HomePage.tsx, src/app/features/cases/routes.tsx, src/app/features/shared/components/layouts/DefaultLayout/DefaultLayout.tsx, src/app/features/shared/components/organisms/navigation/DefaultNavigation.tsx
Get rid of all 'lorem ipsum' links in navigation
=> chore: clean up navigation

src/app/features/cases/components/organisms/FormCreate/scaffold.ts, src/app/features/cases/components/organisms/FormEdit/scaffold.ts
Available fields are:
- startdatum
- einddatum
- zaaktype
- omschrijving
=> chore: removed unnecessary fields

src/__generated__/apiSchema.d.ts, src/app/features/cases/components/organisms/Form/scaffold.ts, src/app/features/cases/components/organisms/TableCases/TableCases.tsx, src/app/features/cases/components/pages/edit/hooks/useEditPage.ts, src/app/features/shared/components/molecules/Form/CaseStatusField/CaseStatusField.tsx, src/app/features/shared/components/molecules/Form/ScaffoldField.tsx, src/app/state/state/GlobalStateProvider.tsx, src/app/state/state/globalState.ts
Introduced a `CaseStatus`-field. 
NOTE: backend is not ready yet.
=> feat: introduced case-status-field

src/app/features/cases/components/organisms/TableCases/TableCases.tsx, src/app/features/shared/components/molecules/Table/Table.stories.tsx, src/app/features/shared/components/molecules/Table/Table.tsx
Placeholder for table when there are no values
=> feat: placeholder for table

.env.test, .gitignore, cypress.json, cypress/README.md, cypress/integration/cases.test.ts, cypress/plugins/index.ts, cypress/support/commands.ts, cypress/support/index.ts, cypress/support/types.d.ts, cypress/tsconfig.json, package-lock.json, package.json, src/app/features/cases/components/pages/edit/EditPage.tsx, src/app/features/shared/components/molecules/Modal/ConfirmModal.tsx
Introduced the first cypress e2e test
=> feat: introduced first cypress e2e test

nginx.conf
=> Devops/deploy acceptance 

.env.production
Environment variables for AUTH and GATEWAY
=> chore: change env for acc

.github/workflows/on-pull-request.yml
=> chore: remove build from build steps

.env.acceptance, .env.production, Dockerfile, nginx.conf, package.json
- Make two builds. One for acceptance, one for production.
=> Acceptance, production build

cypress/integration/cases.test.ts, src/__generated__/apiSchema.d.ts, src/app/features/cases/components/organisms/TableCases/TableCases.tsx, src/app/features/cases/components/pages/edit/EditPage.tsx, src/app/features/cases/components/pages/edit/hooks/useEditPage.ts, src/app/state/rest/index.ts
Backend now uses field `identification` instead of `id`.
Fixes e2e tests
=> chore: switched from case 'id' to case 'identification'

.env.development
The callback url for mock login for local development was changed to the same as "fixxx-looplijsten-frontend", but the .env.development wasn't changed. This PR fixes that
=> Update .env.development to reflect change in react routing

public/icons/Info.svg, src/app/features/shared/components/molecules/InfoHeading/InfoButton.tsx, src/app/features/shared/components/molecules/InfoHeading/InfoHeading.tsx
Add button with Info icon
Eventually the Icon / .svg should come from ASC. See https://github.com/Amsterdam/amsterdam-styled-components/pull/1122
=> Add Info button

.env.development
Should allow to develop locally and bypass Grip again
=> Fix local development settings

src/app/features/addresses/components/molecules/AddressMenu/AddressMenu.tsx, src/app/features/addresses/components/pages/cases/CasesPage.tsx, src/app/features/addresses/components/pages/detail/DetailPage.tsx, src/app/features/addresses/components/pages/details/DetailsPage.tsx, src/app/features/addresses/components/pages/index/IndexPage.tsx, src/app/features/addresses/components/pages/people/PeoplePage.tsx, src/app/features/addresses/routes.tsx, src/app/features/cases/components/organisms/BagDetails/BagDetails.tsx, src/app/features/cases/components/organisms/PermitDetails/PermitDetails.tsx, src/app/features/cases/components/pages/details/DetailsPage.tsx
- Fill address pages
- Some layout fixes
=> Content & layout

src/app/config/routes.tsx, src/app/config/utils/routesToRouteConfig.ts, src/app/features/addresses/components/atoms/NavBlock/NavBlock.tsx, src/app/features/addresses/components/molecules/AddressMenu/AddressMenu.tsx, src/app/features/addresses/components/molecules/BreadCrumbs/BreadCrumbs.tsx, src/app/features/addresses/components/pages/cases/CasesPage.tsx, src/app/features/addresses/components/pages/detail/DetailPage.tsx, src/app/features/addresses/components/pages/details/DetailsPage.tsx, src/app/features/addresses/components/pages/index/IndexPage.tsx, src/app/features/addresses/components/pages/people/PeoplePage.tsx, src/app/features/addresses/routes.tsx, src/app/features/permits/components/pages/index/IndexPage.tsx, src/app/features/shared/routing/find.ts
- BreadCrumbs component
- Maps the path to a Route and reads title, icon and link from routing config
=> BreadCrumbs component

src/app/features/addresses/components/molecules/BreadCrumbs/BreadCrumbs.tsx
- Fix styling
- Make last item non clickable
=> BreadCrumbs

src/app/features/addresses/components/atoms/NavBlock/NavBlock.tsx, src/app/features/addresses/components/molecules/AddressMenu/AddressMenu.tsx
- Display counter
- Add permitDetails counter
=> Nav Block Counter

package-lock.json, package.json, src/app/features/addresses/components/pages/cases/CasesPage.tsx, src/app/features/addresses/components/pages/index/IndexPage.tsx, src/app/features/addresses/components/pages/people/PeoplePage.tsx, src/app/features/cases/components/organisms/Panorama/PanoramaPreview.tsx, src/app/features/cases/components/organisms/Panorama/hooks/useRect.ts, src/app/features/permits/components/pages/index/IndexPage.tsx, src/app/state/rest/custom/usePanoramaByBagId/usePanoramaByBagId.tsx, src/app/state/rest/index.ts
- Display panorama over full width
- Display area before image is loaded
=> Feature Panorama

src/app/features/addresses/components/atoms/NavBlock/NavBlock.tsx, src/app/features/addresses/components/molecules/Heading/Heading.tsx, src/app/features/addresses/components/pages/cases/CasesPage.tsx, src/app/features/addresses/components/pages/details/DetailsPage.tsx, src/app/features/addresses/components/pages/people/PeoplePage.tsx, src/app/features/permits/components/pages/index/IndexPage.tsx, src/app/features/shared/components/organisms/HeadingWithIcon/HeadingWithIcon.tsx
- Read address heading and icon from routing config
=> Feature Address Heading

src/app/features/addresses/components/atoms/AddressDisplay/AddressDisplay.tsx, src/app/features/addresses/components/atoms/AddressHeader/AddressHeader.tsx, src/app/features/addresses/components/molecules/BreadCrumbs/BreadCrumbs.tsx, src/app/features/addresses/components/organisms/AddressSuffixSwitcher/ShowOtherAddressesButton.tsx, src/app/features/addresses/components/pages/cases/CasesPage.tsx, src/app/features/addresses/components/pages/details/DetailsPage.tsx, src/app/features/addresses/components/pages/index/IndexPage.tsx, src/app/features/addresses/components/pages/people/PeoplePage.tsx, src/app/features/cases/components/organisms/PermitDetails/PermitDetails.tsx, src/app/features/cases/components/organisms/Residents/Residents.tsx, src/app/features/cases/components/organisms/TableCases/TableCases.tsx, src/app/features/cases/components/pages/details/DetailsPage.tsx, src/app/features/cases/components/pages/edit/EditPage.tsx, src/app/features/cases/components/pages/index/IndexPage.tsx, src/app/features/permits/components/pages/index/IndexPage.tsx, src/app/features/search/components/organisms/SearchWrapper/SearchWrapper.tsx, src/app/features/search/components/pages/index/IndexPage.tsx, src/app/features/shared/components/atoms/ActionButtonWrap/ActionButtonWrap.tsx, src/app/features/shared/components/atoms/Grid/Row.tsx, src/app/features/shared/components/atoms/Heading/Heading.tsx, src/app/features/shared/components/atoms/MainWrapper/MainWrapper.tsx, src/app/features/shared/components/molecules/Details/Details.tsx, src/app/features/shared/components/molecules/InfoHeading/InfoHeading.tsx, src/app/features/shared/components/organisms/DetailHeader/DetailHeader.tsx, src/app/features/shared/components/organisms/HeadingWithIcon/HeadingWithIcon.tsx, src/app/features/shared/components/pages/NotFoundPage.tsx
- Responsive page layout spacing 
- Add default bottom spacing to `<Row>`
- Remove other irregular vertical spacings from components
=> Styling mobile

src/__generated__/apiSchema.d.ts, src/app/features/addresses/components/molecules/AddressMenu/AddressMenu.tsx, src/app/features/addresses/components/organisms/People/People.tsx, src/app/features/addresses/components/organisms/Residents/Residents.tsx, src/app/state/rest/custom/useResidentsByBagId/useResidentsByBagId.ts, src/app/state/rest/index.ts, src/app/state/rest/provider/ApiProvider.tsx
=> Bag Residents

src/app/features/cases/components/organisms/CaseTimeline/TimelineContainer.tsx, src/app/features/cases/components/organisms/CaseTimeline/TimelineThreadSet.tsx, src/app/features/shared/components/atoms/DateDay/DateDay.tsx, src/app/features/shared/components/atoms/DateDisplay/DateDisplay.tsx, src/app/features/shared/components/atoms/DayDisplay/DayDisplay.tsx
=> Fixes timeline

src/app/state/rest/hooks/useApiRequest.ts
https://sentry.data.amsterdam.nl/sentry/zaken-frontend/issues/2675093/
https://sentry.data.amsterdam.nl/sentry/zaken-frontend/issues/2675094/
=> Fix for undefined error

src/app/components/addresses/AddressSuffixSwitcher/OtherAddressesTable.tsx, src/app/components/search/SearchResults/SearchResults.tsx
Dit zou moeten werken en wordt goed opgepakt in de backend :)
=> Use the adresseerbaar_object_id for BAG objects

src/app/pages/cases/details/DetailsPage.tsx, src/app/pages/cases/details/hooks/useExistingCase.tsx
This should fix the incorrect showing of the 404 page
=> Check for 404 error

src/app/pages/cases/details/hooks/useExistingCase.tsx
Should fix Sentry event 910ba13326244068a6910d6fa68af4f8
=> Add optionality

src/app/components/case/visits/CreateForm/CreateForm.tsx
Should fix https://sentry.data.amsterdam.nl/sentry/zaken-frontend/issues/2682442/?environment=acceptance
=> Check for authors data

src/app/components/addresses/AddressHeader/AddressHeader.tsx
Should fix https://sentry.data.amsterdam.nl/sentry/zaken-frontend/issues/2692480/
=> Check if response has result, plus some clean up

cypress/fixtures/addcase.json, cypress/fixtures/address.json, cypress/integration/addCase/vakantieverhuur/add_case_anonymous_no_ad.spec.js, cypress/integration/addCase/vakantieverhuur/add_case_errors.js, cypress/integration/addCase/vakantieverhuur/add_case_not_anonymous_ad.spec.js, package-lock.json
Changed address and naming of tests
=> All tests succeeded

.gitignore, package-lock.json, package.json, src/app/components/help/HelpContent/CustomTooltip.tsx, src/app/components/tasks/Tasks/Tasks.tsx
Notable changes:
- Added missing `jsdom` package to `package.json`
- Added empty `config/env.js` to prevent local console errors;
- Added basic (inline) styling for tooltips, so they look consistent (even when used inside an `h2`);
---
=> Minor repo and frontend tweaks
